version: '3.8'

services:
  fastapi_app:
    container_name: fastapi_container
    build: .
    tty: True
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app  # Mount the local directory to /code/app in the container

  postgres:
    image: postgres:16rc1
    container_name: postgres_database
    environment:
      POSTGRES_DB: FizjoMarcin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
