version: '3.8'

services:
  fastapi_app:
    container_name: fastapi_container
    build: .
    tty: True
    ports:
      - "8000:8000"
    volumes:
      - I:\Programming\Python\FizjoMarcin\FizjoMarcin\app:/code/app

  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: postgres_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
