version: '3.8'

services:
  fastapi_app:
    build:
      context: ./
    container_name: fastapi_container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"] 

  postgres:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_DB: FizjoMarcin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
